### PR TITLE
prevent duplicates issues to show up in sonar

### PR DESCRIPTION
**Pull request by jmecosta**
for some reasons we got duplicated issues showing up in sonar, solved by ensuring only a unique issue is created

### CODE REVIEW

**Comment by dbolkensteyn** [comment]
Thanks @jmecosta for this pull request.
Do you mean that inspectcode itself reports the same issue multiple times? Which build of it are you using, and on which rule do you see duplicates?

**Comment by jmecosta** [comment]
i dont know anymore, it was a couple of months ago so likely a outdated version of resharper also. I forgot about this, now was updating the c# plugin and notice this changes and decided to make the pr

the vs bootstrapper was off, and resharper was run only once for all the solution so am inclined to say resharper was to be blame 

 ive applied this and we havent seen this again, we also upgraded the cli also so perhaps there is no issues now, but best safe than sorry anyway.

**Comment by dbolkensteyn** [comment]
I'll close this as I've never seen this in a R# myself: inspectcode.exe was in a beta stange (and perhaps still is?) and is very rapidly evolving.

They should definitely fix this on their side.

**Comment by jmecosta** [comment]
Yep its OK to close

**Pull request closed without merging**
